In [ ]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("MCO2 Dataset (full).xlsx")

In [7]:
df.head(10)

word_id  sentence_id                                           sentence  \
0        1            0  Matapos ang matagumpay na mga konsultasyon kas...   
1        2            0  Matapos ang matagumpay na mga konsultasyon kas...   
2        3            0  Matapos ang matagumpay na mga konsultasyon kas...   
3        4            0  Matapos ang matagumpay na mga konsultasyon kas...   
4        5            0  Matapos ang matagumpay na mga konsultasyon kas...   
5        6            0  Matapos ang matagumpay na mga konsultasyon kas...   
6        7            0  Matapos ang matagumpay na mga konsultasyon kas...   
7        8            0  Matapos ang matagumpay na mga konsultasyon kas...   
8        9            0  Matapos ang matagumpay na mga konsultasyon kas...   
9       10            0  Matapos ang matagumpay na mga konsultasyon kas...   

                                 context          word label special_tags  \
0                 Matapos ang matagumpay       Matapos   FIL          NaN   
1              Matapos ang matagumpay na           ang   FIL          NaN   
2          Matapos ang matagumpay na mga    matagumpay   FIL          NaN   
3     ang matagumpay na mga konsultasyon            na   FIL          NaN   
4  matagumpay na mga konsultasyon kasama           mga   FIL          NaN   
5         na mga konsultasyon kasama ang  konsultasyon   FIL          NaN   
6        mga konsultasyon kasama ang pro        kasama   FIL          NaN   
7     konsultasyon kasama ang pro sports           ang   FIL          NaN   
8     kasama ang pro sports stakeholders           pro   ENG          NaN   
9          ang pro sports stakeholders ,        sports   ENG          NaN   

   is_correct  corrected_label  corrected_special_tags  is_dirty  notes  
0         NaN              NaN                     NaN       NaN    NaN  
1         NaN              NaN                     NaN       NaN    NaN  
2         NaN              NaN                     NaN       NaN    NaN  
3         NaN              NaN                     NaN       NaN    NaN  
4         NaN              NaN                     NaN       NaN    NaN  
5         NaN              NaN                     NaN       NaN    NaN  
6         NaN              NaN                     NaN       NaN    NaN  
7         NaN              NaN                     NaN       NaN    NaN  
8         NaN              NaN                     NaN       NaN    NaN  
9         NaN              NaN                     NaN       NaN    NaN

In [25]:
df = df.dropna(subset=['word']).copy()




# i placed this since corrected_label has null values since di pa navavalidate lahat ng labels

df['final_label'] = df['corrected_label'].fillna(df['label'])
df.head(10)

word_id  sentence_id                                           sentence  \
0        1            0  Matapos ang matagumpay na mga konsultasyon kas...   
1        2            0  Matapos ang matagumpay na mga konsultasyon kas...   
2        3            0  Matapos ang matagumpay na mga konsultasyon kas...   
3        4            0  Matapos ang matagumpay na mga konsultasyon kas...   
4        5            0  Matapos ang matagumpay na mga konsultasyon kas...   
5        6            0  Matapos ang matagumpay na mga konsultasyon kas...   
6        7            0  Matapos ang matagumpay na mga konsultasyon kas...   
7        8            0  Matapos ang matagumpay na mga konsultasyon kas...   
8        9            0  Matapos ang matagumpay na mga konsultasyon kas...   
9       10            0  Matapos ang matagumpay na mga konsultasyon kas...   

                                 context          word label special_tags  \
0                 Matapos ang matagumpay       Matapos   FIL          NaN   
1              Matapos ang matagumpay na           ang   FIL          NaN   
2          Matapos ang matagumpay na mga    matagumpay   FIL          NaN   
3     ang matagumpay na mga konsultasyon            na   FIL          NaN   
4  matagumpay na mga konsultasyon kasama           mga   FIL          NaN   
5         na mga konsultasyon kasama ang  konsultasyon   FIL          NaN   
6        mga konsultasyon kasama ang pro        kasama   FIL          NaN   
7     konsultasyon kasama ang pro sports           ang   FIL          NaN   
8     kasama ang pro sports stakeholders           pro   ENG          NaN   
9          ang pro sports stakeholders ,        sports   ENG          NaN   

   is_correct  corrected_label  corrected_special_tags  is_dirty  notes  \
0         NaN              NaN                     NaN       NaN    NaN   
1         NaN              NaN                     NaN       NaN    NaN   
2         NaN              NaN                     NaN       NaN    NaN   
3         NaN              NaN                     NaN       NaN    NaN   
4         NaN              NaN                     NaN       NaN    NaN   
5         NaN              NaN                     NaN       NaN    NaN   
6         NaN              NaN                     NaN       NaN    NaN   
7         NaN              NaN                     NaN       NaN    NaN   
8         NaN              NaN                     NaN       NaN    NaN   
9         NaN              NaN                     NaN       NaN    NaN   

  final_label mapped_label  
0         FIL          FIL  
1         FIL          FIL  
2         FIL          FIL  
3         FIL          FIL  
4         FIL          FIL  
5         FIL          FIL  
6         FIL          FIL  
7         FIL          FIL  
8         ENG          ENG  
9         ENG          ENG

In [26]:
df['label'].value_counts()

label
FIL    32312
ENG     4187
SYM     3264
UNK     1767
NUM      354
Name: count, dtype: int64

In [27]:
# i just checked why there are NAN values in the word column

df['word'].isna().sum()


np.int64(0)

In [ ]:
# why tf are there NAN values in the word column
# this should be labeled as dirty siguro in the first place ill just drop em
df[df['word'].isna()]


word_id  sentence_id  \
1471      1472           82   
1479      1480           82   
1929      1930          110   
3104      3105          171   
6418      6419          379   
7660      7661          476   
8146      8147          511   
8690      8691          541   
8972      8973          557   
9064      9065          563   
10982    10983          692   
16045    16046          993   
16059    16060          993   
17619    17620         1089   
22224    22225         1378   
23519    23520         1459   
24379    24380         1514   
24388    24389         1514   
35004    35005         2168   
38157    38158         2352   
38515    38516         2376   
38880    38881         2395   
41482    41483         2579   

                                                sentence  \
1471   Naiyak ako doon sa sinabi ng tatay na " Anak ,...   
1479   Naiyak ako doon sa sinabi ng tatay na " Anak ,...   
1929      "  Inay , maghahanap po ako bukas ng trabaho .   
3104   Sabihin mo : " Kaya hindi ba kayo mangingilag ...   
6418            Gusto Niya nakagawa ka pa ng mabuti . "    
7660   Ang naturang halaman na tila " one-night " onl...   
8146        "  Ako ang matsong daga na babantay sa 'yo .   
8690   Siguro sa isang linggo tatlong araw lang na me...   
8972    Natawa ako kay mona " Kelan ka pa ngka jowa ? "    
9064               Ako po si Justin ang pangalan ko . "    
10982  "  Ipagpaumanhin ninyo pero gusto ko lang kumu...   
16045  They say " Nagcacancer yan kasi umalis sa igle...   
16059  They say " Nagcacancer yan kasi umalis sa igle...   
17619  Bakit ba kasi nag-celebrate ng New Year kasama...   
22224  Sabihin mo : " Tunay na ako ay sinaway na suma...   
23519  "  Tinulungan niyang isara ang zipper ng damit...   
24379  "  Huwag kang gumawa ng iskandalo rito , "  an...   
24388  "  Huwag kang gumawa ng iskandalo rito , "  an...   
35004              Kaunti ang pinasasalamatan ninyo ! "    
38157  Pagkatapos ng ilang araw , sasabihin sa 'yo , ...   
38515  "  Dahil wala pang kumalas sa grupo ni Dorong ...   
38880  Kaya umiwas ka sa kanila at magsabi ka : " Kap...   
41482                             " Mga dilawan tae ! "    

                      context word label special_tags  is_correct  \
1471                , "  at "  NaN   SYM          NaN         NaN   
1479                     . "   NaN   SYM          NaN         NaN   
1929                "  Inay ,  NaN   SYM          NaN         NaN   
3104                     ? "   NaN   SYM          NaN         NaN   
6418                     . "   NaN   SYM          NaN         NaN   
7660            , "  dahil sa  NaN   SYM          NaN         NaN   
8146               "  Ako ang  NaN   SYM          NaN         NaN   
8690         , "  ani Rosendo  NaN   SYM          NaN         NaN   
8972                     ? "   NaN   SYM          NaN         NaN   
9064                     . "   NaN   SYM          NaN         NaN   
10982  "  Ipagpaumanhin ninyo  NaN   SYM          NaN         NaN   
16045        , "  Namatay yan  NaN   SYM          NaN         NaN   
16059                    . "   NaN   SYM          NaN         NaN   
17619                    ? "   NaN   SYM          NaN         NaN   
22224                    . "   NaN   SYM          NaN         NaN   
23519    "  Tinulungan niyang  NaN   SYM          NaN         NaN   
24379           "  Huwag kang  NaN   SYM          NaN         NaN   
24388           , "  ani Vida  NaN   SYM          NaN         NaN   
35004                    ! "   NaN   SYM          NaN         NaN   
38157                    ? "   NaN   SYM          NaN         NaN   
38515           "  Dahil wala  NaN   SYM          NaN         NaN   
38880                    ! "   NaN   SYM          NaN         NaN   
41482                    ! "   NaN   SYM          NaN         NaN   

       corrected_label  corrected_special_tags  is_dirty  notes final_label  \
1471               NaN                     NaN       NaN    NaN         SYM   
1479  

In [ ]:
# since we only have 3 labels, we map all subcategories to main categories ('FIL', 'ENG', 'OTH')
def  map_lables(tag):
    
    if pd.isna(tag):
        return 'OTH'
    tag = tag.upper()
    if tag == 'FIL'or tag == 'CS':
        return 'FIL'
    if tag == 'ENG':
        return 'ENG'
    
    return 'OTH'

df['mapped_label'] = df['final_label'].apply(map_lables)
df['mapped_label'].value_counts()

mapped_label
FIL    32312
OTH     5408
ENG     4187
Name: count, dtype: int64

In [ ]:
# this part will be for feature engineering and our model training
#prompt engineering at its finest. we can always add features

def extract_features_for_word(word, prev_word=None, prev_pred=None):
    """
    Extracts features from a single word for language classification.
    Includes:
      - basic linguistic stats
      - Filipino & English morphology
      - character-level bigrams
      - simple context from previous word/prediction
    """

    # --- SAFETY CHECK ---
    if not isinstance(word, str):
        word = "" if pd.isna(word) else str(word)

    lower = word.lower()
    num_chars = len(word)
    num_vowels = sum(ch in "aeiou" for ch in lower)
    vowel_ratio = (num_vowels / num_chars) if num_chars > 0 else 0.0

    # --- BASE FEATURES ---
    feats = {
        "length": num_chars,
        "num_vowels": num_vowels,
        "vowel_ratio": vowel_ratio,
        "is_capitalized": 1 if (num_chars > 0 and word[0].isupper()) else 0,
        "is_all_caps": 1 if (num_chars > 0 and word.isupper()) else 0,

        # Filipino morphology
        "starts_mag": 1 if lower.startswith("mag") else 0,
        "starts_nag": 1 if lower.startswith("nag") else 0,
        "starts_ni":  1 if lower.startswith("ni")  else 0,
        "has_ng":     1 if "ng" in lower else 0,
        "has_mga":    1 if "mga" in lower else 0,

        # English morphology
        "ends_ing":   1 if lower.endswith("ing") else 0,
        "ends_ed":    1 if lower.endswith("ed") else 0,
        "ends_s":     1 if lower.endswith("s")  else 0,
        "has_th":     1 if "th" in lower else 0,
        "has_sh":     1 if "sh" in lower else 0,
        "has_tion":   1 if "tion" in lower else 0,

        # Symbols/numbers
        "has_digit":  1 if any(ch.isdigit() for ch in word) else 0,
        "has_punct":  1 if any(not ch.isalnum() for ch in word) else 0,
    }

    # --- CHARACTER BIGRAMS (2-letter sequences) ---
    # we could add trigrams or other n-grams later if needed pero im testing for bigrams first
    for i in range(len(lower) - 1):
        bigram = lower[i:i+2]
        feats[f"bi_{bigram}"] = 1

    # --- OPTIONAL CONTEXTUAL FEATURES ---
    # literally just checks the previous word's last letter and previous prediction (if it exists)
    if prev_word:
        feats["prev_ends_vowel"] = 1 if prev_word[-1].lower() in "aeiou" else 0
    else:
        feats["prev_ends_vowel"] = 0

    if prev_pred:
        feats[f"prev_pred_{prev_pred}"] = 1
    else:
        feats["prev_pred_NONE"] = 1

    return feats

In [29]:
# we'll apply the feature extraction to our df

feature_dicts = []
prev_word, prev_pred = None, None

for i, row in df.iterrows():
    
    feats = extract_features_for_word(row['word'], prev_word, prev_pred)
    feature_dicts.append(feats)
    
    prev_word = row['word']
    prev_pred = row['mapped_label']

In [31]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=True)
X = vec.fit_transform(feature_dicts)
y = df['mapped_label'].values

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


# testing 70% of the data
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

#15/15 split
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [33]:
dtc = DecisionTreeClassifier(criterion='gini',max_depth=10, random_state=0, min_samples_leaf=2)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=2, random_state=0)

In [ ]:
print("Training Accuracy:", dtc.score(X_train, y_train))    
print("Validation Accuracy:", dtc.score(X_val, y_val))
print("Test Accuracy:", dtc.score(X_test, y_test))


Training Accuracy: 0.9098506037246743
Validation Accuracy: 0.9045042177303836
Test Accuracy: 0.9113480821263727


In [43]:
# just a simple report

from sklearn.metrics import classification_report, confusion_matrix

y_val_pred = dtc.predict(X_val)
y_test_pred = dtc.predict(X_test)


print("Validation Report:")
print(classification_report(y_val, y_val_pred))

print("Validation Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("\nTest Report:")
print(classification_report(y_test, y_test_pred))

print("Test Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))


Validation Report:
              precision    recall  f1-score   support

         ENG       0.73      0.51      0.60       637
         FIL       0.91      0.98      0.95      4904
         OTH       0.95      0.74      0.83       742

    accuracy                           0.90      6283
   macro avg       0.86      0.74      0.79      6283
weighted avg       0.90      0.90      0.90      6283

Validation Confusion Matrix:
[[ 328  296   13]
 [  81 4808   15]
 [  42  153  547]]

Test Report:
              precision    recall  f1-score   support

         ENG       0.73      0.53      0.61       599
         FIL       0.92      0.98      0.95      4874
         OTH       0.97      0.77      0.86       810

    accuracy                           0.91      6283
   macro avg       0.87      0.76      0.81      6283
weighted avg       0.91      0.91      0.91      6283

Test Confusion Matrix:
[[ 318  271   10]
 [  81 4782   11]
 [  39  145  626]]
